import type { Group } from "./types"

export const mockGroups: Group[] = [
  {
    id: "1",
    name: "開発ツール",
    color: "oklch(0.55 0.22 264)",
    icon: "💻",
    isFavorite: true,
    order: 0,
    createdAt: new Date("2025-01-01"),
    lastOpened: new Date("2025-01-10"),
    links: [
      {
        id: "1-1",
        title: "GitHub",
        url: "https://github.com",
        favicon: "https://github.com/favicon.ico",
        order: 0,
      },
      {
        id: "1-2",
        title: "Vercel",
        url: "https://vercel.com",
        favicon: "https://vercel.com/favicon.ico",
        order: 1,
      },
      {
        id: "1-3",
        title: "Stack Overflow",
        url: "https://stackoverflow.com",
        favicon: "https://stackoverflow.com/favicon.ico",
        order: 2,
      },
    ],
  },
  {
    id: "2",
    name: "デザイン",
    color: "oklch(0.65 0.25 330)",
    icon: "🎨",
    isFavorite: true,
    order: 1,
    createdAt: new Date("2025-01-02"),
    lastOpened: new Date("2025-01-09"),
    links: [
      {
        id: "2-1",
        title: "Figma",
        url: "https://figma.com",
        favicon: "https://figma.com/favicon.ico",
        order: 0,
      },
      {
        id: "2-2",
        title: "Dribbble",
        url: "https://dribbble.com",
        favicon: "https://dribbble.com/favicon.ico",
        order: 1,
      },
      {
        id: "2-3",
        title: "Behance",
        url: "https://behance.net",
        favicon: "https://behance.net/favicon.ico",
        order: 2,
      },
    ],
  },
  {
    id: "3",
    name: "ニュース",
    color: "oklch(0.6 0.2 180)",
    icon: "📰",
    isFavorite: false,
    order: 2,
    createdAt: new Date("2025-01-03"),
    links: [
      {
        id: "3-1",
        title: "Hacker News",
        url: "https://news.ycombinator.com",
        favicon: "https://news.ycombinator.com/favicon.ico",
        order: 0,
      },
      {
        id: "3-2",
        title: "TechCrunch",
        url: "https://techcrunch.com",
        favicon: "https://techcrunch.com/favicon.ico",
        order: 1,
      },
    ],
  },
  {
    id: "4",
    name: "SNS",
    color: "oklch(0.65 0.22 45)",
    icon: "📱",
    isFavorite: false,
    order: 3,
    createdAt: new Date("2025-01-04"),
    links: [
      {
        id: "4-1",
        title: "Twitter",
        url: "https://twitter.com",
        favicon: "https://twitter.com/favicon.ico",
        order: 0,
      },
      {
        id: "4-2",
        title: "LinkedIn",
        url: "https://linkedin.com",
        favicon: "https://linkedin.com/favicon.ico",
        order: 1,
      },
    ],
  },
]
